// Color theme configurations for AsyaKitap
// Based on tweakcn themes: https://tweakcn.com

export interface ColorTheme {
  name: string
  label: string
  colors: {
    light: ThemeColors
    dark: ThemeColors
  }
}

interface ThemeColors {
  background: string
  foreground: string
  card: string
  cardForeground: string
  popover: string
  popoverForeground: string
  primary: string
  primaryForeground: string
  secondary: string
  secondaryForeground: string
  muted: string
  mutedForeground: string
  accent: string
  accentForeground: string
  destructive: string
  border: string
  input: string
  ring: string
  chart1: string
  chart2: string
  chart3: string
  chart4: string
  chart5: string
  sidebar: string
  sidebarForeground: string
  sidebarPrimary: string
  sidebarPrimaryForeground: string
  sidebarAccent: string
  sidebarAccentForeground: string
  sidebarBorder: string
  sidebarRing: string
}

export const colorThemes: ColorTheme[] = [
  {
    name: "asya",
    label: "Asya (Varsayılan)",
    colors: {
      light: {
        background: "#F8FAFC",
        foreground: "#0F172A",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        popover: "#FFFFFF",
        popoverForeground: "#0F172A",
        primary: "#ff364e",
        primaryForeground: "#FFFFFF",
        secondary: "#F1F5F9",
        secondaryForeground: "#1E293B",
        muted: "#F1F5F9",
        mutedForeground: "#64748B",
        accent: "#ffeff4",
        accentForeground: "#ba2839",
        destructive: "#ba2839",
        border: "#E2E8F0",
        input: "#E2E8F0",
        ring: "#ff364e",
        chart1: "#ff364e",
        chart2: "#f6344b",
        chart3: "#e33046",
        chart4: "#f38f9b",
        chart5: "#ffeff4",
        sidebar: "#1E293B",
        sidebarForeground: "#F8FAFC",
        sidebarPrimary: "#ff364e",
        sidebarPrimaryForeground: "#FFFFFF",
        sidebarAccent: "#334155",
        sidebarAccentForeground: "#F8FAFC",
        sidebarBorder: "#334155",
        sidebarRing: "#ff364e",
      },
      dark: {
        background: "#0F172A",
        foreground: "#F8FAFC",
        card: "#1E293B",
        cardForeground: "#F8FAFC",
        popover: "#1E293B",
        popoverForeground: "#F8FAFC",
        primary: "#ff364e",
        primaryForeground: "#FFFFFF",
        secondary: "#334155",
        secondaryForeground: "#F8FAFC",
        muted: "#334155",
        mutedForeground: "#94A3B8",
        accent: "#334155",
        accentForeground: "#F8FAFC",
        destructive: "#ba2839",
        border: "#334155",
        input: "#334155",
        ring: "#ff364e",
        chart1: "#ff364e",
        chart2: "#f6344b",
        chart3: "#e33046",
        chart4: "#f38f9b",
        chart5: "#ffeff4",
        sidebar: "#020617",
        sidebarForeground: "#F8FAFC",
        sidebarPrimary: "#ff364e",
        sidebarPrimaryForeground: "#FFFFFF",
        sidebarAccent: "#1E293B",
        sidebarAccentForeground: "#F8FAFC",
        sidebarBorder: "#1E293B",
        sidebarRing: "#ff364e",
      },
    },
  },
  {
    name: "modern-minimal",
    label: "Modern Minimal",
    colors: {
      light: {
        background: "#FFFFFF",
        foreground: "#09090B",
        card: "#FFFFFF",
        cardForeground: "#09090B",
        popover: "#FFFFFF",
        popoverForeground: "#09090B",
        primary: "#18181B",
        primaryForeground: "#FAFAFA",
        secondary: "#F4F4F5",
        secondaryForeground: "#18181B",
        muted: "#F4F4F5",
        mutedForeground: "#71717A",
        accent: "#F4F4F5",
        accentForeground: "#18181B",
        destructive: "#EF4444",
        border: "#E4E4E7",
        input: "#E4E4E7",
        ring: "#18181B",
        chart1: "#18181B",
        chart2: "#3F3F46",
        chart3: "#52525B",
        chart4: "#71717A",
        chart5: "#A1A1AA",
        sidebar: "#FAFAFA",
        sidebarForeground: "#09090B",
        sidebarPrimary: "#18181B",
        sidebarPrimaryForeground: "#FAFAFA",
        sidebarAccent: "#F4F4F5",
        sidebarAccentForeground: "#18181B",
        sidebarBorder: "#E4E4E7",
        sidebarRing: "#18181B",
      },
      dark: {
        background: "#09090B",
        foreground: "#FAFAFA",
        card: "#09090B",
        cardForeground: "#FAFAFA",
        popover: "#09090B",
        popoverForeground: "#FAFAFA",
        primary: "#FAFAFA",
        primaryForeground: "#18181B",
        secondary: "#27272A",
        secondaryForeground: "#FAFAFA",
        muted: "#27272A",
        mutedForeground: "#A1A1AA",
        accent: "#27272A",
        accentForeground: "#FAFAFA",
        destructive: "#7F1D1D",
        border: "#27272A",
        input: "#27272A",
        ring: "#D4D4D8",
        chart1: "#FAFAFA",
        chart2: "#D4D4D8",
        chart3: "#A1A1AA",
        chart4: "#71717A",
        chart5: "#52525B",
        sidebar: "#09090B",
        sidebarForeground: "#FAFAFA",
        sidebarPrimary: "#FAFAFA",
        sidebarPrimaryForeground: "#18181B",
        sidebarAccent: "#27272A",
        sidebarAccentForeground: "#FAFAFA",
        sidebarBorder: "#27272A",
        sidebarRing: "#D4D4D8",
      },
    },
  },
  {
    name: "amber-minimal",
    label: "Amber",
    colors: {
      light: {
        background: "#FFFBEB",
        foreground: "#451A03",
        card: "#FFFFFF",
        cardForeground: "#451A03",
        popover: "#FFFFFF",
        popoverForeground: "#451A03",
        primary: "#D97706",
        primaryForeground: "#FFFFFF",
        secondary: "#FEF3C7",
        secondaryForeground: "#92400E",
        muted: "#FEF3C7",
        mutedForeground: "#92400E",
        accent: "#FDE68A",
        accentForeground: "#78350F",
        destructive: "#DC2626",
        border: "#FDE68A",
        input: "#FDE68A",
        ring: "#D97706",
        chart1: "#D97706",
        chart2: "#F59E0B",
        chart3: "#FBBF24",
        chart4: "#FCD34D",
        chart5: "#FDE68A",
        sidebar: "#78350F",
        sidebarForeground: "#FFFBEB",
        sidebarPrimary: "#F59E0B",
        sidebarPrimaryForeground: "#FFFFFF",
        sidebarAccent: "#92400E",
        sidebarAccentForeground: "#FFFBEB",
        sidebarBorder: "#92400E",
        sidebarRing: "#F59E0B",
      },
      dark: {
        background: "#1C1917",
        foreground: "#FAFAF9",
        card: "#292524",
        cardForeground: "#FAFAF9",
        popover: "#292524",
        popoverForeground: "#FAFAF9",
        primary: "#F59E0B",
        primaryForeground: "#1C1917",
        secondary: "#44403C",
        secondaryForeground: "#FAFAF9",
        muted: "#44403C",
        mutedForeground: "#A8A29E",
        accent: "#57534E",
        accentForeground: "#FAFAF9",
        destructive: "#7F1D1D",
        border: "#44403C",
        input: "#44403C",
        ring: "#F59E0B",
        chart1: "#F59E0B",
        chart2: "#FBBF24",
        chart3: "#FCD34D",
        chart4: "#FDE68A",
        chart5: "#FEF3C7",
        sidebar: "#0C0A09",
        sidebarForeground: "#FAFAF9",
        sidebarPrimary: "#F59E0B",
        sidebarPrimaryForeground: "#1C1917",
        sidebarAccent: "#292524",
        sidebarAccentForeground: "#FAFAF9",
        sidebarBorder: "#292524",
        sidebarRing: "#F59E0B",
      },
    },
  },
  {
    name: "ocean-breeze",
    label: "Ocean",
    colors: {
      light: {
        background: "#F0F9FF",
        foreground: "#0C4A6E",
        card: "#FFFFFF",
        cardForeground: "#0C4A6E",
        popover: "#FFFFFF",
        popoverForeground: "#0C4A6E",
        primary: "#0284C7",
        primaryForeground: "#FFFFFF",
        secondary: "#E0F2FE",
        secondaryForeground: "#075985",
        muted: "#E0F2FE",
        mutedForeground: "#0369A1",
        accent: "#BAE6FD",
        accentForeground: "#0C4A6E",
        destructive: "#DC2626",
        border: "#BAE6FD",
        input: "#BAE6FD",
        ring: "#0284C7",
        chart1: "#0284C7",
        chart2: "#0EA5E9",
        chart3: "#38BDF8",
        chart4: "#7DD3FC",
        chart5: "#BAE6FD",
        sidebar: "#0C4A6E",
        sidebarForeground: "#F0F9FF",
        sidebarPrimary: "#0EA5E9",
        sidebarPrimaryForeground: "#FFFFFF",
        sidebarAccent: "#075985",
        sidebarAccentForeground: "#F0F9FF",
        sidebarBorder: "#075985",
        sidebarRing: "#0EA5E9",
      },
      dark: {
        background: "#0F172A",
        foreground: "#F0F9FF",
        card: "#1E293B",
        cardForeground: "#F0F9FF",
        popover: "#1E293B",
        popoverForeground: "#F0F9FF",
        primary: "#38BDF8",
        primaryForeground: "#0C4A6E",
        secondary: "#334155",
        secondaryForeground: "#F0F9FF",
        muted: "#334155",
        mutedForeground: "#94A3B8",
        accent: "#475569",
        accentForeground: "#F0F9FF",
        destructive: "#7F1D1D",
        border: "#334155",
        input: "#334155",
        ring: "#38BDF8",
        chart1: "#38BDF8",
        chart2: "#0EA5E9",
        chart3: "#0284C7",
        chart4: "#0369A1",
        chart5: "#075985",
        sidebar: "#020617",
        sidebarForeground: "#F0F9FF",
        sidebarPrimary: "#38BDF8",
        sidebarPrimaryForeground: "#0C4A6E",
        sidebarAccent: "#1E293B",
        sidebarAccentForeground: "#F0F9FF",
        sidebarBorder: "#1E293B",
        sidebarRing: "#38BDF8",
      },
    },
  },
  {
    name: "catppuccin",
    label: "Catppuccin",
    colors: {
      light: {
        background: "#EFF1F5",
        foreground: "#4C4F69",
        card: "#E6E9EF",
        cardForeground: "#4C4F69",
        popover: "#E6E9EF",
        popoverForeground: "#4C4F69",
        primary: "#8839EF",
        primaryForeground: "#FFFFFF",
        secondary: "#DCE0E8",
        secondaryForeground: "#4C4F69",
        muted: "#DCE0E8",
        mutedForeground: "#6C6F85",
        accent: "#CCD0DA",
        accentForeground: "#4C4F69",
        destructive: "#D20F39",
        border: "#CCD0DA",
        input: "#CCD0DA",
        ring: "#8839EF",
        chart1: "#8839EF",
        chart2: "#EA76CB",
        chart3: "#1E66F5",
        chart4: "#40A02B",
        chart5: "#FE640B",
        sidebar: "#E6E9EF",
        sidebarForeground: "#4C4F69",
        sidebarPrimary: "#8839EF",
        sidebarPrimaryForeground: "#FFFFFF",
        sidebarAccent: "#DCE0E8",
        sidebarAccentForeground: "#4C4F69",
        sidebarBorder: "#CCD0DA",
        sidebarRing: "#8839EF",
      },
      dark: {
        background: "#1E1E2E",
        foreground: "#CDD6F4",
        card: "#313244",
        cardForeground: "#CDD6F4",
        popover: "#313244",
        popoverForeground: "#CDD6F4",
        primary: "#CBA6F7",
        primaryForeground: "#1E1E2E",
        secondary: "#45475A",
        secondaryForeground: "#CDD6F4",
        muted: "#45475A",
        mutedForeground: "#A6ADC8",
        accent: "#585B70",
        accentForeground: "#CDD6F4",
        destructive: "#F38BA8",
        border: "#45475A",
        input: "#45475A",
        ring: "#CBA6F7",
        chart1: "#CBA6F7",
        chart2: "#F5C2E7",
        chart3: "#89B4FA",
        chart4: "#A6E3A1",
        chart5: "#FAB387",
        sidebar: "#11111B",
        sidebarForeground: "#CDD6F4",
        sidebarPrimary: "#CBA6F7",
        sidebarPrimaryForeground: "#1E1E2E",
        sidebarAccent: "#313244",
        sidebarAccentForeground: "#CDD6F4",
        sidebarBorder: "#313244",
        sidebarRing: "#CBA6F7",
      },
    },
  },
  {
    name: "violet-bloom",
    label: "Violet",
    colors: {
      light: {
        background: "#FAF5FF",
        foreground: "#581C87",
        card: "#FFFFFF",
        cardForeground: "#581C87",
        popover: "#FFFFFF",
        popoverForeground: "#581C87",
        primary: "#7C3AED",
        primaryForeground: "#FFFFFF",
        secondary: "#F3E8FF",
        secondaryForeground: "#6B21A8",
        muted: "#F3E8FF",
        mutedForeground: "#7C3AED",
        accent: "#E9D5FF",
        accentForeground: "#581C87",
        destructive: "#DC2626",
        border: "#E9D5FF",
        input: "#E9D5FF",
        ring: "#7C3AED",
        chart1: "#7C3AED",
        chart2: "#8B5CF6",
        chart3: "#A78BFA",
        chart4: "#C4B5FD",
        chart5: "#DDD6FE",
        sidebar: "#581C87",
        sidebarForeground: "#FAF5FF",
        sidebarPrimary: "#A78BFA",
        sidebarPrimaryForeground: "#FFFFFF",
        sidebarAccent: "#6B21A8",
        sidebarAccentForeground: "#FAF5FF",
        sidebarBorder: "#6B21A8",
        sidebarRing: "#A78BFA",
      },
      dark: {
        background: "#1E1B2E",
        foreground: "#F5F3FF",
        card: "#2E2B3F",
        cardForeground: "#F5F3FF",
        popover: "#2E2B3F",
        popoverForeground: "#F5F3FF",
        primary: "#A78BFA",
        primaryForeground: "#1E1B2E",
        secondary: "#3E3B4F",
        secondaryForeground: "#F5F3FF",
        muted: "#3E3B4F",
        mutedForeground: "#A5A3B8",
        accent: "#4E4B5F",
        accentForeground: "#F5F3FF",
        destructive: "#7F1D1D",
        border: "#3E3B4F",
        input: "#3E3B4F",
        ring: "#A78BFA",
        chart1: "#A78BFA",
        chart2: "#8B5CF6",
        chart3: "#7C3AED",
        chart4: "#6D28D9",
        chart5: "#5B21B6",
        sidebar: "#14121F",
        sidebarForeground: "#F5F3FF",
        sidebarPrimary: "#A78BFA",
        sidebarPrimaryForeground: "#1E1B2E",
        sidebarAccent: "#2E2B3F",
        sidebarAccentForeground: "#F5F3FF",
        sidebarBorder: "#2E2B3F",
        sidebarRing: "#A78BFA",
      },
    },
  },
]

export const DEFAULT_COLOR_THEME = "asya"

export function getThemeByName(name: string): ColorTheme | undefined {
  return colorThemes.find((theme) => theme.name === name)
}
